# Configuración del sitio para GitHub Pages
title: "Biblioteca Completa de Seguridad Digital Familiar"
description: "Recursos integrales para crear entornos digitales seguros para niños y adolescentes"
baseurl: "/GuiaParaPadres" # dejar vacío si el repo es nombre-usuario.github.io, caso contrario /nombre-repositorio
url: "https://walalapancho.github.io" # cambiar por tu URL de GitHub Pages

# Configuración de Jekyll
theme: minima
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Configuraciones adicionales
lang: es
timezone: America/Santiago

# Navegación principal
header_pages:
  - index.md
  - INDICE-INTERACTIVO.md
  - guia-maestros.md
  - taller-familiar.md
  - fuentes-referencias.md

# Metadatos del sitio
author:
  name: "Biblioteca de Seguridad Digital"
  email: ""

# SEO y redes sociales
social:
  - platform: github
    user_url: "https://github.com/walalapancho/GuiaParaPadres"

# Configuración de recursos estáticos y contenido

# Configuración de contenido
show_excerpts: true
date_format: "%d/%m/%Y"

# Excluir archivos del build
exclude:
  - LICENSE
  - README.md
  - CHANGELOG.md
  - node_modules
  - package*.json
  - yarn.lock
  - Dockerfile
  - docker-compose.yml
  - .git*
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile*
  - node_modules/
  - "*.gem"
  - "*.gemspec"
  - check_links.py

# Configuración de colecciones para mejor organización
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Valores por defecto
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/js"
    values:
      js: true
  - scope:
      path: "assets/css"
    values:
      css: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      lang: es
      image: false
      comments: false
      search: true
      nav_exclude: false
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
      lang: es
      image: false
      comments: false
      search: true
      nav_exclude: false

# Configuración de redirecciones
redirect_from:
  enabled: true
  # Usar _redirects para las redirecciones personalizadas
  collections: true
